version: 2
jobs:
  build:

    docker:
      - image: circleci/openjdk:8-jdk-stretch
      - image: circleci/postgres:9.6.3-alpine
      - image: circleci/node:6.10
      - image: circleci/python:3-node
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test

    steps:

      - checkout

      - restore_cache:
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}

      - run: mvn package

      - run:
          name: "Update Node.js and npm + install yarn"
          command: |
            curl -sSL "https://nodejs.org/dist/v11.10.0/node-v11.10.0-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v11.10.0-linux-x64/bin/node
            curl https://www.npmjs.com/install.sh | sudo bash
            curl -o- -L https://yarnpkg.com/install.sh | bash

        # change working directory to backend, and then run mvn test

# --------------------------------------------------------------------------

#      - run :
#         name: Front end - npm runtest
#         command: npm install
#         shell: /bin/bash
#         working_directory: ~/project/FrontEnd
#
#      - run:
#          name: Front end - install yarn
#          command: npm install yarn
#          shell: /bin/bash
#          working_directory: ~/project/FrontEnd
#
#      - run:
#          name: Front end - install yarn
#          command: yarn init
#          shell: /bin/bash
#          working_directory: ~/project/FrontEnd
#
#      - run:
#          name: Front end - yarn test
#          command: yarn test
#          shell: /bin/bash
#          working_directory: ~/project/FrontEnd

# --------------------------------------------------------------------------

#      - run :
#          name: Front end - npm runtest
#          command: npm install
#          shell: /bin/bash
#          working_directory: ~/project/FrontEnd
#      - run :
#          name: Front end - npm runtest
#          command: npm run test
#          shell: /bin/bash
#          working_directory: ~/project/FrontEnd

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/demo-java-spring-0.0.1-SNAPSHOT.jar
          #path: target/ms_profiles-0.0.1-SNAPSHOT.jar

