version: 2
jobs:
  build:
    working_directory: ~/majorproject-2-thurs-18-30-3/BackEnd/ms_profiles

    docker:
      - image: circleci/openjdk:8-jdk-stretch
      - image: circleci/postgres:9.6.3-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test

    steps:

      - checkout

      - restore_cache:
          key: majorproject-2-thurs-18-30-3-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: majorproject-2-thurs-18-30-3-{{ checksum "pom.xml" }}

      - run: mvn package

      - store_test_results:
          path: majorproject-2-thurs-18-30-3/BackEnd/ms_profiles/target/surefire-reports

      - store_artifacts:
          path: majorproject-2-thurs-18-30-3/BackEnd/ms_profiles/target/ms_profiles-0.0.1-SNAPSHOT.jar